name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # In order to make gatsby incremental build works, it's necessary .cache
      # and public folder.
      - name: Gatsby Cache Folder
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-gatsby

      - name: Gatsby Public Folder
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-public-gatsby

      - name: Deploy To Github Pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: page
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          NODE_ENV: production
      # - name: Deploy to Server        
      #   uses: easingthemes/ssh-deploy@v2.1.1        
      #   env:   
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}          
      #     ARGS: "-rltgoDzvO --delete"          
      #     REMOTE_USER: ${{ secrets.DEPLOY_USER }} 
      #     REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}          
      #     SOURCE: "public/"          
      #     TARGET: "/home/nginx/blog"
      - name: Trigger Profile Update
        run: |-
          curl -i -u gemryan:${{secrets.ACCESS_TOKEN}} -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/w1zd/w1zd/actions/workflows/update-pofile.yml/dispatches -d '{"ref":"main"}'
